### ISSUE TITLE
Forked ex-navigation as local package in project - @providesModule naming collision issue

### ISSUE THREAD

**Issue by annelorraineuy** [exponent/ex-navigation#428]
As a time-constraint measure I've had to fork ex-navigation. One of the reasons was to replace the burger menu icon since I found no way before. Anyway, so I downloaded the forked zip and unzipped the directory into a top-level `forked_packages` and referenced it using `file:./forked_packages/ex-navigation` as you can see below.

```
{
  ...,
  "dependencies": {
    "@exponent/ex-navigation": "file:./forked_packages/ex-navigation", <-- here
    "@gblejman/react-native-device": "file:./forked_packages/react-native-device",
    "apisauce": "^0.10.0",
    "date-fns": "^1.20.1",
    "iap-receipt-validator": "^1.0.6",
    "immutable": "^3.8.1",
    "lodash": "^4.17.2",
    "qs": "^6.3.0",
    "react": "15.4.1",
    "react-native": "^0.39.2",
    "react-native-billing": "^2.3.0",
    "react-native-device-detection": "^0.1.3",
    "react-native-firebase-analytics": "1.0.6",
    "react-native-firebase-crash-report": "1.1.1",
    "react-native-fs": "2.0.1-rc.2",
    "react-native-in-app-utils": "^4.0.0",
    "react-native-linear-gradient": "file:./forked_packages/react-native-linear-gradient",
    "react-native-orientation": "file:./forked_packages/react-native-orientation",
    "react-native-root-modal": "^1.0.7",
    "react-native-sound": "^0.9.0",
    "react-native-text": "^0.0.4",
    "react-native-uuid": "^1.4.9",
    "react-native-vector-icons": "file:./forked_packages/react-native-vector-icons",
    "react-native-video": "0.9.0",
    "react-native-wkwebview-reborn": "file:./forked_packages/react-native-wkwebview",
    "react-navigation": "^1.0.0-beta.1",
    "react-redux": "^4.4.6",
    "react-timer-mixin": "^0.13.3",
    "redux": "^3.6.0",
    "redux-saga": "^0.13.0",
    "reduxsauce": "^0.2.0",
    "seamless-immutable": "^6.3.0",
    "validatorjs": "file:./forked_packages/validatorjs"
  },
  "devDependencies": {
    "babel-jest": "17.0.2",
    "babel-preset-react-native": "1.9.0",
    "babel-preset-react-native-stage-0": "^1.0.1",
    "eslint": "^3.10.2",
    "eslint-config-airbnb": "^13.0.0",
    "eslint-plugin-import": "^2.2.0",
    "eslint-plugin-jsx-a11y": "^2.2.3",
    "eslint-plugin-react": "^6.7.1",
    "flow-bin": "^0.35.0",
    "jest": "17.0.3",
    "react-test-renderer": "15.4.1",
    "redux-logger": "^2.7.4"
  },
  "jest": {
    "preset": "react-native"
  },
  "rnpm": {
    "assets": [
      "src/assets/fonts"
    ]
  }
}
```

Installation always looks good using either `npm i` or `yarn`. 
But when I start the packager I get errors from ex-navigation about a naming collision issue from `ExNavigationExample`.

```
Failed to build DependencyGraph: @providesModule naming collision:
  Duplicate module name: ExNavigationExample
  Paths: /Users/annelorraineuy/projects/rooplayNativeMock3/forked_packages/ex-navigation/example-shared-element-transitions/package.json collides with /Users/annelorraineuy/projects/rooplayNativeMock3/forked_packages/ex-navigation/example/package.json

This error is caused by a @providesModule declaration with the same name across two different files.
Error: @providesModule naming collision:
  Duplicate module name: ExNavigationExample
  Paths: /Users/annelorraineuy/projects/rooplayNativeMock3/forked_packages/ex-navigation/example-shared-element-transitions/package.json collides with /Users/annelorraineuy/projects/rooplayNativeMock3/forked_packages/ex-navigation/example/package.json

This error is caused by a @providesModule declaration with the same name across two different files.
    at HasteMap._updateHasteMap (/Users/annelorraineuy/projects/rooplayNativeMock3/node_modules/react-native/packager/react-packager/src/node-haste/DependencyGraph/HasteMap.js:159:13)
    at p.getName.then.name (/Users/annelorraineuy/projects/rooplayNativeMock3/node_modules/react-native/packager/react-packager/src/node-haste/DependencyGraph/HasteMap.js:134:31)
~

```

**Comment by annelorraineuy** [comment]
Removing the folder `example-shared-element-transitions` removed this error. You can close this issue now.
